### ISSUE TITLE
Review the email that gets sent out to new joiners

### ISSUE THREAD

**Issue by samanthasaw** [samanthasaw/womensnetwork#3]
Acceptance criteria: 
• Review the email content 
• Send to Susie for approval

**Comment by samanthasaw** [comment]
Actions from meeting with @owen-beddis 
• Find out who organises the women's network lunch and learns

Decisions from the meeting: 
• Change the subject line
• Remove the 'who is who' content and the 'volunteer opportunities' content
• Remove name of recipient and have the signature generic

**Comment by samanthasaw** [comment]
[Women's network email template.docx](https://github.com/samanthasaw/womensnetwork/files/3836767/Women.s.network.email.template.docx)

@owen-beddis Here's the template, let me know what you think

**Comment by owen-beddis** [comment]
I like the look of it! I've added a few comments here on this file
[Women's Network Email Template.docx](https://github.com/samanthasaw/womensnetwork/files/3837047/Women.s.Network.Email.Template.docx)

**Comment by samanthasaw** [comment]
[Women.s.Network.Email.Template V2 OB SS.docx](https://github.com/samanthasaw/womensnetwork/files/3846921/Women.s.Network.Email.Template.V2.OB.SS.docx)

@owen-beddis I've made changes based on your comments and added a couple of questions for you. Also once I've got a logo from someone I can add that, then once you've checked should be ok to send to Susie

**Comment by owen-beddis** [comment]
[Women.s.Network.Email.Template.V2.OB.SS.docx](https://github.com/samanthasaw/womensnetwork/files/3863146/Women.s.Network.Email.Template.V2.OB.SS.docx)

@samanthasaw - I agree with your comments, I've added one final suggestion but I'm not sure whether it would be possible :)

**Comment by owen-beddis** [comment]
![NHS Digital Womens Network Logo (Blue)-01](https://user-images.githubusercontent.com/57357288/69137265-51252000-0ab4-11ea-9771-b3c3f742f287.png)

@samanthasaw Here is the women's network logo - is it possible for us to resize it?

**Comment by samanthasaw** [comment]
@owen-beddis Yes I think we could say 'on the 28th of the month'

We will add you to our mailing list to receive our bi-monthly newsletter which goes out on the 28th every other month. 

Maybe something like that?

**Comment by samanthasaw** [comment]
@owen-beddis Also Molly Kate McCaffrey has been speaking with comms because the logo doesn't meet branding guidelines. Hoping they get something approved soon. But hopefully we can still use the current logo on the newsletter if nothing is sorted by then

**Comment by samanthasaw** [comment]
@owen-beddis Susie mentioned she wanted the email to mention volunteer opportunities so perhaps we should think about how we could include that? I've had a go at reducing the existing content, let me know what you think 

**Our volunteer opportunities**
 
**Ada Lovelace celebrations**
We are looking for a group of volunteers to organise some events during November to celebrate Ada Lovelace day 2019. 
 
**Purple Lights initiative**
We are looking for volunteers to support this year’s Purple Lights initiative which will take place in Trevelyan Square on Tuesday 3 December. This year’s event will be driving the message of Intersectionality. 

Email womensnetwork@nhs.net if you are interested in volunteering.

**Comment by owen-beddis** [comment]
28th of every other month works well!

Owen Beddis
Graduate User Researcher
Digital Maternity Programme
owen.beddis1@nhs.net<mailto:owen.beddis1@nhs.net>


[cid:image001.jpg@01D57F56.45F31050]

NHS Digital provides information and technology for better health and care.
Find out more about us: www.digital.nhs.uk<http://www.digital.nhs.uk>  | @nhsdigital

**Comment by samanthasaw** [comment]
[Women.s.Network.Email.Template.V3.OB.SS.docx](https://github.com/samanthasaw/womensnetwork/files/3863246/Women.s.Network.Email.Template.V3.OB.SS.docx)

V3 of email template @owen-beddis let me know what you think

**Comment by owen-beddis** [comment]
I like it! Just one suggestion but other than that I think it's pretty much there! 
[Women.s.Network.Email.Template.V3.OB.SS.docx](https://github.com/samanthasaw/womensnetwork/files/3863252/Women.s.Network.Email.Template.V3.OB.SS.docx)

**Comment by samanthasaw** [comment]
[Women.s.Network.Email.Template.V4.OB.SS.docx](https://github.com/samanthasaw/womensnetwork/files/3863281/Women.s.Network.Email.Template.V4.OB.SS.docx)

@owen-beddis If you're happy with this I'll send it over to Susie

**Comment by owen-beddis** [comment]
Happy with it :) @samanthasaw

**Comment by samanthasaw** [comment]
New template now sent over to Susie
